[package]
name = "obsidian_lite"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.9.0", features = ["bot-poise"] }
anyhow = "1.0.68"
poise = "0.5.2"
shuttle-secrets = "0.9.0"
tracing = "0.1.37"
