name: Rust test, lint, format

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Lint
      run: cargo check --verbose
    
    # - name: Run tests
    #   run: cargo test --verbose
    
    - name: Format
      run: cargo fmt --verbose --check
